// Copyright (c) 2013 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Crosswalk Runtime API
namespace runtime {
  callback GetAPIVersionCallback = void (long version);

  interface Functions {
    static void getAPIVersion(GetAPIVersionCallback callback);
  };
};
