{
  'sources': [
    'browser/xwalk_extension_service.cc',
    'browser/xwalk_extension_service.h',
    'browser/xwalk_extension_web_contents_handler.cc',
    'browser/xwalk_extension_web_contents_handler.h',
    'common/xwalk_extension.cc',
    'common/xwalk_extension.h',
    'common/xwalk_extension_external.cc',
    'common/xwalk_extension_external.h',
    'common/xwalk_extension_messages.cc',
    'common/xwalk_extension_messages.h',
    'common/xwalk_extension_runner.cc',
    'common/xwalk_extension_runner.h',
    'common/xwalk_extension_threaded_runner.cc',
    'common/xwalk_extension_threaded_runner.h',
    'public/xwalk_extension_public.h',
    'renderer/xwalk_extension_renderer_controller.cc',
    'renderer/xwalk_extension_renderer_controller.h',
    'renderer/xwalk_extension_render_view_handler.cc',
    'renderer/xwalk_extension_render_view_handler.h',
    'renderer/xwalk_api.js',
  ],
  'includes': [
    'xwalk_js2c.gypi',
  ],
}
