{
  'sources': [
    'browser/cameo_extension.cc',
    'browser/cameo_extension_external.cc',
    'browser/cameo_extension_external.h',
    'browser/cameo_extension.h',
    'browser/cameo_extension_service.cc',
    'browser/cameo_extension_service.h',
    'browser/cameo_extension_web_contents_handler.cc',
    'browser/cameo_extension_web_contents_handler.h',
    'common/cameo_extension_messages.cc',
    'common/cameo_extension_messages.h',
    'public/cameo_extension_public.h',
    'renderer/cameo_extension_renderer_controller.cc',
    'renderer/cameo_extension_renderer_controller.h',
    'renderer/cameo_extension_render_view_handler.cc',
    'renderer/cameo_extension_render_view_handler.h',
  ],
}
