// Copyright (c) 2014 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.xwalk.core.xwview.test;

import java.io.File;
import java.io.FilenameFilter;

import android.app.Activity;
import android.test.suitebuilder.annotation.SmallTest;

import org.chromium.base.test.util.Feature;
import org.chromium.net.test.util.TestWebServer;
import org.xwalk.core.XWalkPreferences;

/**
 * Test suite for XWalkPreferences.PROFILE_NAME.
 */
public class ProfileTest extends XWalkViewTestBase {
    private final static String TEST_PROFILE_NAME = "test-profile";

    private boolean deleteDir(File f) {
        if (f.isDirectory()) {
            File[] files = f.listFiles();
            if (files == null) return true;
            for (File subFile : files) {
                deleteDir(subFile);
            }
        }
        return f.delete();
    }

    @Override
    public void setUp() throws Exception {
        final Activity activity = getActivity();
        String appDataDir = activity.getFilesDir().getParent();
        File userDataDir = new File(appDataDir + File.separator + "app_xwalkcore" +
                File.separator + TEST_PROFILE_NAME);
        File defaultUserDataDir = new File(appDataDir + File.separator + "app_xwalkcore" +
                File.separator + "Default");
        deleteDir(userDataDir);
        deleteDir(defaultUserDataDir);
        XWalkPreferences.setValue(XWalkPreferences.PROFILE_NAME, TEST_PROFILE_NAME);
        XWalkPreferences.setValue(XWalkPreferences.REMOTE_DEBUGGING, true);
        super.setUp();
    }

    @SmallTest
    @Feature({"Profile"})
    public void testCustomizeProfile() throws Throwable {
        TestWebServer webServer = TestWebServer.start();
        try {
            final String testHtml = getFileContent("profile.html");
            final String testPath = "/profile.html";
            final String testUrl = webServer.setResponse(testPath, testHtml, null);

            loadUrlSync(testUrl);
            assertEquals("Profile Test", getTitleOnUiThread());
            // Visiting test WebServer will generate Cache and Cookies, plus the local
            // storage generated by js code, all kinds of user data are covered.
            executeJavaScriptAndWaitForResult("useLocalStorage();");
            final Activity activity = getActivity();
            String appDataDir = activity.getFilesDir().getParent();
            File userDataDir = new File(appDataDir + File.separator + "app_xwalkcore" +
                    File.separator + TEST_PROFILE_NAME);
            File defaultUserDataDir = new File(appDataDir + File.separator + "app_xwalkcore" +
                    File.separator + "Default");
            assertTrue(userDataDir.isDirectory());
            assertFalse(defaultUserDataDir.exists());
        } finally {
            webServer.shutdown();
        }
    }
}
