// Copyright (c) 2013 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Device Capabilities API
namespace device_capabilities {
  dictionary AudioCodec {
    DOMString format;
  };

  dictionary VideoCodec {
    DOMString format;
    boolean hwAccel;
    boolean encode;
  };

  dictionary SystemAVCodecs {
    AudioCodec[] audioCodecs;
    VideoCodec[] videoCodecs;
  };

  dictionary SystemCPU {
    long numOfProcessors;
    DOMString archName;
    double load;
  };

  dictionary SystemMemory {
    // If we use long here, it will overflow.
    double capacity;
    double availCapacity;
  };

  enum StorageUnitType {
    fixed,
    removable,
    unknown
  };

  dictionary StorageUnit {
    DOMString id;
    DOMString name;
    DOMString type;
    double capacity;
  };

  dictionary SystemStorage {
    StorageUnit[] storages;
  };

  callback SystemAVCodecsPromise = void (SystemAVCodecs info, DOMString error);
  callback SystemCPUPromise = void (SystemCPU info, DOMString error);
  callback SystemMemoryPromise = void (SystemMemory info, DOMString error);
  callback SystemStoragePromise = void (SystemStorage info, DOMString error);

  interface Functions {
    static void getAVCodecs(SystemAVCodecsPromise promise);
    static void getCPUInfo(SystemCPUPromise promise);
    static void getMemoryInfo(SystemMemoryPromise promise);
    static void getStorageInfo(SystemStoragePromise promise);

    [nodoc] static DeviceCapabilities deviceCapabilitiesConstructor(DOMString objectId);
  };
};
