// Copyright (c) 2013 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Device Capabilities API
namespace device_capabilities {
  dictionary SystemCPU {
    long numOfProcessors;
    DOMString archName;
    double load;
  };
};
